import type { Metadata } from 'next'
import { Comic_Neue } from 'next/font/google'
import './globals.css'

const comicneue = Comic_Neue({ weight: ['400', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.mygateway.xyz/widget/buttons.css" />
      </head>
      <body className={comicneue.className}>{children}</body>
    </html>
  )
}
